---
- name: Install acl package and prepare Ansible tmpdir
  hosts: all
  gather_facts: true
  become: true

  roles:

    - role: johanneskastl.install_one_or_more_packages
      packages_to_be_installed:
        - acl

  post_tasks:

    - name: Create /var/lib/writefreely/.ansible/tmp/
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: writefreely
        group: writefreely
        mode: '0700'
      loop:
        - /var/lib/writefreely/.ansible/
        - /var/lib/writefreely/.ansible/tmp/
