---
- name: Start writefreely
  hosts: all
  gather_facts: true
  become: true

  handlers:

    - name: Restart the systemd service
      ansible.builtin.service:
        name: writefreely
        state: restarted
      when:
        - not writefreely_service_started.changed | bool

  tasks:

    - name: Start the service
      ansible.builtin.service:
        name: writefreely
        state: started
      register: writefreely_service_started

    - name: Enable the service
      ansible.builtin.service:
        name: writefreely
        enabled: true
