---
- name: Start writefreely
  hosts: all
  gather_facts: true
  become: true

  handlers:

    - name: Restart the systemd service
      ansible.builtin.service:
        name: writefreely
        state: restarted
      when:
        - not writefreely_service_started.changed | bool

  tasks:

    - name: Create the systemd unit
      ansible.builtin.template:
        src: writefreely.service.j2
        dest: /etc/systemd/system/writefreely.service
        owner: vagrant
        group: vagrant
        mode: '0644'
      notify:
        - Restart the systemd service

    - name: Start the service
      ansible.builtin.service:
        name: writefreely
        state: started
        daemon_reload: true
      register: writefreely_service_started

    - name: Enable the service
      ansible.builtin.service:
        name: writefreely
        enabled: true
        daemon_reload: true
