---

#
# bootstrap Python311
#

- name: Run playbook-all_nodes-bootstrap_python311.yml
  ansible.builtin.import_playbook: playbook-all_nodes-bootstrap_python311.yml

#
# general configuration
#

- name: Run playbook-all_nodes-create_a_vimrc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: Run playbook-all_nodes-install_tmux.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: Run playbook-all_nodes-minimal_tmux_configuration.yml
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml
