---

#
# bootstrap Python311
#

- name: Run playbook-all_nodes-bootstrap_python311.yml
  ansible.builtin.import_playbook: playbook-all_nodes-bootstrap_python311.yml

#
# general configuration
#

- name: Run playbook-all_nodes-create_a_vimrc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: Run playbook-all_nodes-install_tmux.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: Run playbook-all_nodes-minimal_tmux_configuration.yml
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: Run playbook-all_nodes-minimal_bashrc.yml
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

#
# WriteFreely
#

- name: Run playbook-all_nodes-add_WriteFreely_repo.yml
  ansible.builtin.import_playbook: playbook-all_nodes-add_WriteFreely_repo.yml

- name: Run playbook-all_nodes-install_writefreely.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_writefreely.yml

- name: Run playbook-all_nodes-configure_writefreely.yml
  ansible.builtin.import_playbook: playbook-all_nodes-configure_writefreely.yml

- name: Run playbook-all_nodes-start_writefreely_service.yml
  ansible.builtin.import_playbook: playbook-all_nodes-start_writefreely_service.yml

- name: Run playbook-all_nodes-install_configure_and_start_nginx.yml
  ansible.builtin.import_playbook: playbook-all_nodes-install_configure_and_start_nginx.yml
