---
- name: Install writefreely using the upstream binary
  hosts: all
  gather_facts: true
  become: true
  become_user: writefreely

  tasks:

    - name: Create the configuration
      ansible.builtin.template:
        src: config.ini.j2
        dest: /var/lib/writefreely/config.ini
        owner: writefreely
        group: writefreely
        mode: '0644'

    - name: Run writefreely db init
      ansible.builtin.command:
        cmd: 'writefreely db init'
        creates: /var/lib/writefreely/writefreely.db
        chdir: /var/lib/writefreely/

    - name: Run writefreely keys generate
      ansible.builtin.command:
        cmd: 'writefreely keys generate'
        creates: /var/lib/writefreely/keys/cookies_enc.aes256
        chdir: /var/lib/writefreely/

    - name: Create the vagrant-libvirt user
      ansible.builtin.shell:
        cmd: 'writefreely user create --admin vagrant-libvirt:atotallysecurepassword && touch /var/lib/writefreely/.user_was_created_by_ansible'
        creates: /var/lib/writefreely/.user_was_created_by_ansible
        chdir: /var/lib/writefreely/
