---
- name: Start writefreely
  hosts: all
  gather_facts: true
  become: true

  handlers:

    - name: Restart the systemd service
      ansible.builtin.service:
        name: writefreely
        state: restarted
      when:
        - not writefreely_service_started.changed | bool

  tasks:

    - name: Start the service
      ansible.builtin.service:
        name: writefreely
        state: started
      register: writefreely_service_started

    - name: Enable the service
      ansible.builtin.service:
        name: writefreely
        enabled: true

    - name: Wait for URL to be available
      delegate_to: localhost
      become: false
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8080"
      register: result
      until: "result.status == 200"
      retries: 31
      delay: 10

    - name: URL
      ansible.builtin.debug:
        msg: "URL: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8080"

    - name: WriteFreely credentials
      ansible.builtin.debug:
        msg: "Use the username 'vagrant-libvirt' and the password 'atotallysecurepassword'"
